from experimento import Experimento # Clase Tienda
exp1 = Experimento(m=10, pasos=50*10)
exp1.correr()
exp1.graficar_inventario()
exp1.graficar_precio()
exp1.graficar_ganancia()
# rep1 = exp1.reporte_liquidez()
# rep2 = exp1.reportes()
# exp1.archivar_reportes('archivo.xls')
# print(rep1)
# exp1.graficar_precio()